[package]
name = "packybara"
version = "0.1.0"
authors = ["jgerber <jlgerber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.5.0-alpha.2"
tokio = "0.2.1"
postgres = "0.17.0-alpha.2"
levelspec = {git = "https://github.com/jlgerber/rust-lspec.git"}
strum = "0.16.0"
strum_macros = "0.16.0"